### ISSUE TITLE
Run it but I got blank black screen

### ISSUE THREAD

**Issue by Vic152** [devsnd/matrix-curses#4]
Setup: win 7 64
Python: Python 3.4.4 (v3.4.4:737efcadf5a6
curses-2.2+utf8-cp34-cp34m-win_amd64.whl

I run the script but all I see is a black screen.

**Comment by Vic152** [comment]
Traceback (most recent call last):
  File "C:\Users\stone\py\learningPython.py", line 243, in <module>
    main()
  File "C:\Users\stone\py\learningPython.py", line 195, in main
    scr = curses.initscr()
  File "C:\Python34\lib\curses\__init__.py", line 30, in initscr
    fd=_sys.__stdout__.fileno())
AttributeError: 'NoneType' object has no attribute 'fileno'
